name: dataleon_flutter
description: Flutter SDK for Dataleon verification.
version: 1.0.1
homepage: https://github.com/dataleonlabs/dataleon_flutter.git
repository: https://github.com/dataleonlabs/dataleon_flutter.git
issue_tracker: https://github.com/dataleonlabs/dataleon_flutter/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.dataleon.flutter
        pluginClass: DataleonFlutterPlugin
      ios:
        pluginClass: DataleonFlutterPlugin
